[project]
name = "bad-therapy-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "httpx>=0.27.0",
    "ipykernel>=6.29.5",
    "langchain[openai]>=0.3.25",
    "langgraph>=0.4.3",
    "pydantic>=2.0.0",
]
